version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: iot-safety-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: iot_safety_db
      MYSQL_USER: root_base
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - iot-safety-network


  backend:
    image: quandt74959/thinhdt:latest
    container_name: iot-safety-backend
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/iot_safety_db
      SPRING_DATASOURCE_USERNAME: root_base
      SPRING_DATASOURCE_PASSWORD: 123456

      JWT_SECRET: ${JWT_SECRET:change-me-in-production}

      FIREBASE_CONFIG_PATH: /app/secrets/firebase-service-account.json

      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER}

    volumes:
      - ./secrets/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro

    networks:
      - iot-safety-network
volumes:
  mysql_data:

networks:
  iot-safety-network:
    driver: bridge